version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10.3
      - image: circleci/postgres:9.4
    working_directory: /go/src/github.com/pokedextracker/api.pokedextracker.com
    steps:
      - restore_cache:
          keys:
            - source-v1-{{ .Branch }}-{{ .Revision }}
            - source-v1-{{ .Branch }}-
            - source-v1-
      - checkout
      - save_cache:
          key: source-v1-{{ .Branch }}-{{ .Revision }}
          paths:
            - /go/src/github.com/pokedextracker/api.pokedextracker.com/.git
      - restore_cache:
          keys:
            - vendor-v1-{{ checksum ".go-version" }}-{{ checksum "Gopkg.lock" }}
            - vendor-v1-{{ checksum ".go-version" }}-
            - vendor-v1-
      - run:
          name: Install tools
          command: make setup
      - run:
          name: Install dependencies
          command: make install
      - save_cache:
          key: vendor-v1-{{ checksum ".go-version" }}-{{ checksum "Gopkg.lock" }}
          paths:
            - /go/src/github.com/pokedextracker/api.pokedextracker.com/vendor
    #   - run:
    #       name: Run linter
    #       command: make lint
      - run:
          name: Run tests
          command: make test
      - run:
          name: Enforce coverage
          command: make enforce
      - store_artifacts:
          path: coverage.out
