version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11rc2
        environment:
          ENVIRONMENT: test
      - image: circleci/postgres:9.4
        environment:
          POSTGRES_USER: pokedex_tracker_admin
          POSTGRES_DB: pokedex_tracker_test
          POSTGRES_PASSWORD: ""
    working_directory: ~/api.pokedextracker.com
    steps:
      - restore_cache:
          keys:
            - source-v2-{{ .Branch }}-{{ .Revision }}
            - source-v2-{{ .Branch }}-
            - source-v2-
      - checkout
      - save_cache:
          key: source-v2-{{ .Branch }}-{{ .Revision }}
          paths:
            - ~/api.pokedextracker.com/.git
      - restore_cache:
          keys:
            - vendor-v2-{{ checksum ".go-version" }}-{{ checksum "go.sum" }}
            - vendor-v2-{{ checksum ".go-version" }}-
            - vendor-v2-
      - run:
          name: Set up project
          command: make setup
      - run:
          name: Install dependencies
          command: make install
      - save_cache:
          key: vendor-v2-{{ checksum ".go-version" }}-{{ checksum "go.sum" }}
          paths:
            - ~/.cache/go-build
    #   - run:
    #       name: Run linter
    #       command: make lint
      - run:
          name: Run migrations
          command: make migrate
      - run:
          name: Run tests
          command: make test
      - run:
          name: Enforce coverage
          command: make enforce
      - store_artifacts:
          path: coverage.out
